# -*- coding: utf-8 -*-
"""nhan_dien_cac_loai_hoa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYIc-LjpsqLsnDGN7EFqipnZRaR975jQ
"""

from google.colab import drive
drive.mount('/content/drive')

from keras.models import Sequential
from keras.layers import Input, Conv2D, MaxPool2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.utils import load_img
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 1. Khai báo đường dẫn và xử lý dữ liệu
train_dir = '/content/drive/MyDrive/nhận diện các loài hoa (1)' # ĐỔI ĐƯỜNG DẪN Ở ĐÂY
img_width, img_height = 200, 200 # Đổi thành 200x200 cho nhẹ và chuẩn form
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1/255,
    shear_range=0.2,
    zoom_range=0.2,
    height_shift_range=0.2,
    width_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical'
)

model = Sequential([
    Input(shape=(img_width, img_height, 3)),
    Conv2D(33, (3, 3), activation='relu'),
    MaxPool2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(6, activation='softmax')
])

model.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])
model.summary()

epochs = 200
history = model.fit(train_generator, epochs=epochs)



path = "/content/hoasen.png"
img = load_img(path, target_size=(img_width, img_height))
plt.imshow(img)
img = np.array(img)
img = img/255.0
img = img.reshape(1, img_width, img_height, 3)

prediction = np.argmax(model.predict(img))
class_labels = {v:k for k, v in train_generator.class_indices.items()}
dish_name = class_labels[prediction]
print(f"Loại hoa tiên đoán: {dish_name}")

